# Generated by Django 4.1.3 on 2022-11-25 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cliente", models.CharField(max_length=35)),
                ("consulta", models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("rol", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tecnico", models.CharField(max_length=100)),
                ("respuesta", models.CharField(max_length=240)),
                (
                    "id_consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administracion.consulta",
                    ),
                ),
            ],
        ),
    ]
