# Generated by Django 4.1.3 on 2022-11-25 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0002_comuna_estado_remove_respuesta_id_consulta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cliente", models.CharField(max_length=35)),
                ("consulta", models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tecnico", models.CharField(max_length=100)),
                ("respuesta", models.CharField(max_length=240)),
                (
                    "id_consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administracion.consulta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("rol", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Comuna",
        ),
        migrations.DeleteModel(
            name="Estado",
        ),
    ]
